
version: "3"

services:


  uwsgi:

    build:
      context: .
      dockerfile: uwsgi.dockerfile
      args:
        HOST: 0.0.0.0
        PORT: 9000

    networks:
      - common

    restart: always


  nginx:

    depends_on:
      - uwsgi

    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        NGINX_PORT: 80
        UWSGI_HOST: uwsgi
        UWSGI_PORT: 9000

    networks:
      - common

    ports:
      - 80:80

    restart: always


networks:
  common:
